app:
  name: example
  host: localhost
  port: 9000

logger:
  level: debug # debug | info | warn | error
  path: ./logs
  caller: true

database:
  type: mysql
  dsn: # [rw, r]
    - 'root:root@tcp(127.0.0.1:3306)/myapp?charset=utf8mb4&parseTime=True&loc=Local'
    # - 'root:root@tcp(127.0.0.1:3307)/myapp?charset=utf8mb4&parseTime=True&loc=Local'
  debug: true
  migrator: false

redis:
  addr: 127.0.0.1:6379
  password: root
  db: 1
